version: '2'
services:
  ledger:
    build: ./
    environment:
      - RAILS_ENV=minipod
      - DATABASE_URL=mysql2://root:mysql@db:3306/ledger_minipod
      - STATSD_HOST=http://localhost
      - STATSD_PORT=2085
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=123456
    command: /bin/bash -x /app/minipod/assure_test_dependencies.sh
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=ledger_minipod

  test:
    build:
      context: ./
      dockerfile: ./Dockerfile.test
    command: /bin/bash run_test.bash
    environment:
      - APP_HOST=ledger
    links:
      - db
      - ledger
    depends_on:
      - db
      - ledger
