version: '2'
services:
  ledger:
    build: ./
    environment:
      - RAILS_ENV=minipod
      - DATABASE_URL=mysql2://root@db:3306/ledger_minipod
      - STATSD_HOST=http://localhost
      - STATSD_PORT=2085
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=123456
    command: /bin/bash -x /app/minipod/assure_test_dependencies.sh
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - db

  db:
    image: runnable/mysql:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: echo "wow" && echo "start" && sleep 99999999 # gosu mysql mysqld --skip-grant-tables

  test:
    build: ./Dockerfile.test
    command: echo "..." && echo "Start tests" && sleep 9999 # /bin/bash run_test.bash
    environment:
      - APP_HOST=ledger
    links:
      - db
      - ledger
